#!/bin/sh
# Shows diffs for conflicts and provides options for resolving them
# Also auto-merges jrnl conflicts if JOURNAL is set
# Depends: synct dif
name="${0%-*}"
stats() {
  stat --format '%.10y %n %sB - birth %.10w' "$@"
}
test "$1" = "-q" && quick=-q && shift
if test "$#" -gt 0
  then
    for arg; do
      orig="$(echo "$arg" | $name-unarchive)"
      if test -n "$quick"
      then stats "$orig" "$arg"
      else
        if diff "$orig" "$arg" >/dev/null
        then reply=d
        else ( stats "$orig" "$arg"; dif "$orig" "$arg" ) |
            less --RAW-CONTROL-CHARS --quit-on-intr --quit-if-one-screen
          test "$?" -eq "2" && exit 1
          echo "y|r to restore, n|d to delete, m to git-merge, e to ediff"
          read reply
        fi
        case "$reply" in
          (y|r) $name-restore "$arg";;
          (n|d) rm -v "$arg";;
          (m) touch /tmp/empty && git merge-file "$orig" /tmp/empty "$arg" && "${EDITOR:-vi}" "$orig" && rm "$arg";;
          (e) emacsclient -a "" --eval "(ediff-files \"$orig\" \"$arg\")"
        esac
      fi
    done
  else
    test "$JOURNAL" && find "$JOURNAL" -name '*sync-conflict*.txt' -exec sh -c 'basename {} | cut -d. -f1 | xargs -i% jrnl % --import --file {}' \; -delete
    find -name '.stfolder' -prune -o -name '*sync-conflict*' -exec "$0" $quick '{}' \;
fi
