#!/bin/sh
# Trims the path of an archived or conflicted file to its original
# For syncthing and Resilio Sync
if test "$#" -eq 0
then cat
else for arg; do realpath "$arg"; done
fi | sed 's|\.sync/Archive/\(.\+\)\.[[:digit:]]\+$|\1|;
     s|\.sync/Archive/||;
     s|~[[:digit:]]\{8\}-[[:digit:]]\{6\}\(\..\{2,4\}\)|\1|;
     s|\.stversions/||;
     s|\.stfolder/archive/||;
     s|\.sync-conflict-[[:digit:]]\+-[[:digit:]]\+-[A-Z0-9]\+||
     s|\B#\(.*\)#$|\1|
     s|\.pacnew$||
     s|\.pacsave$||
     s|\.bak$||
     s|\~$||'
